name: vale

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  vale-runner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Vale Linter
        uses: errata-ai/vale-action@reviewdog
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: website/recipes/
          vale_flags: "--config=vale/vale.ini"
          reporter: github-pr-check
          fail_on_error: true
          filter_mode: nofilter
