---
name: Linting with Vale on pull request
on: [pull_request]
 
jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
            fail_on_error: true
            vale_flags: --config=vale/vale.ini
            version: 3.4.2
            files: all
            debug: false
