name: Vale
on:
  - pull_request

jobs:
  vale:
    name: vale
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: Execute Vale
        run: |
          wget -q https://github.com/errata-ai/vale/releases/download/v3.5.0/vale_3.5.0_Linux_64-bit.tar.gz
          mkdir bin && tar -xvzf vale_3.5.0_Linux_64-bit.tar.gz -C bin
          bin/vale --config=./vale/vale.ini \
            --no-exit \
            website/recipes
