name: Vale
on:
  - pull_request

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: '["website/recipes"]'
          vale_flags: "--config=./vale/vale.ini"
          filter_mode: added
          fail_on_error: false
